### ISSUE TITLE
Release v1.0

### ISSUE THREAD

**Issue by radioflash** [rofinn/FilePathsBase.jl#116]
There was recently some recent discussion on the Julia Slack about package versioning: https://julialang.slack.com/archives/C6M4DQA5P/p1617216478072500

Several people expressed their concerns with the <v1.0 versions that are still widespread in the Julia library ecosystem.
These have several issues:

- These packages are bending the Semantic versioning rules, because they *de-facto* define a public API (which SemVer requires to be >=v1.0) 
- <v1.0 packages are unable to cleanly express (non-breaking) feature growth (every change ist either a PATCH release, or "breaking")
- The transition to v1.0 is necessarily a breaking change, which often does not make any sense

I have compiled a more detailed overview [here](https://github.com/radioflash/julia-library-versioning)

I created this issue to raise awareness and to hopefully trigger such a release in the near future!

This is part of a larger effort to push packages (especially widely used ones) toward v1.0.

All opinions/discussion/feedback is welcome!

**Comment by rofinn** [comment]
> There was recently some recent discussion on the Julia Slack about package versioning: https://julialang.slack.com/archives/C6M4DQA5P/p1617216478072500

The link to the slack discussion has already been deleted because we only use the free version. Those kinds of conversations are best moved to discourse.

> Several people expressed their concerns with the <v1.0 versions that are still widespread in the Julia library ecosystem.

You're making a pretty blanket statement here with "several people" and "widespread". I think the decision to move to a 1.0 release is and should be made on a case-by-case basis. Often package developers are finding that their prototypes are sufficiently feature-complete to warrant that release.

> - These packages are bending the Semantic versioning rules, because they de-facto define a public API (which SemVer requires to be >=v1.0)

That just isn't true though. The semver.org explicitly states

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

AFAICT, most pre-1.0 packages are informing users that the API should not be considered stable. I think your argument boils down wanting more commitment on stability from maintainers. In some cases that's happening already, folks realize the API has stabilized with no planned breaking changes, so they tag 1.0. I think it's perfectly reasonable to stay pre-1.0 if there are planned/undecided features that are likely to break the API.

> - <v1.0 packages are unable to cleanly express (non-breaking) feature growth (every change ist either a PATCH release, or "breaking")

This isn't entirely accurate either. If you look at most packages you'll often find that releases are either breaking or non-breaking, which for early development makes sense. Folks aren't likely to bother backporting fixes in patch releases for early development software. Inevitably, you'll find that breaking changes are "minor" releases and everything else (non-breaking features and bug fixes) are "patch" releases. Again, this isn't ideal, but seems fine if folks don't want to deal with backporting or deprecation cycles in their software.
 
> - The transition to v1.0 is necessarily a breaking change, which often does not make any sense

Again, this seems like an over simplification. Yes, most maintainers want to get most of their big breaking changes done before 1.0 to minimize headaches, but like I mentioned lots of packages just bump to 1.0 cause everything is stable. 

https://github.com/simonster/Reexport.jl/releases/tag/1.0.0

> I created this issue to raise awareness and to hopefully trigger such a release in the near future!

Sure. There are still several breaking/undecided design issues in the queue, so I'll get to tagging a 1.0 release when I can.

> This is part of a larger effort to push packages (especially widely used ones) toward v1.0.

Fair enough, but this package is only used in a handful of packages according to the registry.
