### ISSUE TITLE
Is there a reason `/` is not exported?

### ISSUE THREAD

**Issue by tfiers** [rofinn/FilePathsBase.jl#157]
I would assume there's no danger of conflict due to Julia's dispatch.

**Comment by rofinn** [comment]
It's not exported because the behaviour `/` in the context of filepaths is completely different then how it's defined in base. The argument made by core Julia devs is that we'd be randomly changing the meaning of `/` just by having `FilePathsBase` loaded in your environment. As a compromise, we've defined it as a completely separate unexported function that falls back to `Base./`. For reference, here's the original issue that triggered the change.

https://github.com/rofinn/FilePathsBase.jl/issues/53

**Comment by tfiers** [comment]
thanks for the pointer!
And for the great package :)

**Comment by tfiers** [comment]
Just for future reference and understanding (based on Jeff Bezanson's point 3 [here](https://github.com/rofinn/FilePathsBase.jl/issues/53#issuecomment-611028873)):
If I understand correctly, the reason it is not desired to have `/(::AbstractPath, …)` exported by default,
is that this would cause all code using `/` to have longer compilation times.
