### ISSUE TITLE
`SystemPath` should be an abstract type

### ISSUE THREAD

**Issue by nickrobinson251** [rofinn/FilePathsBase.jl#43]
Currently it is a `Union`
https://github.com/rofinn/FilePathsBase.jl/blob/b44425a0661709beff2aa17eeae0e9b96bb0a147/src/system.jl#L7

But `Union`s are not friendly to extension (see `StridedMatrix` for the all-time most annoyinng case)

Can be solved by 
```julia
abstract type SystemPath <: AbstactPath

struct PosixPath <: SystemPath
   ...etc
```

**Comment by oxinabox** [comment]
I agree, I generally feel like most `Unions` should either be abstract types, or if that bullet is fired, traits.

```
"""
    SystemPath

An abstract type that represents a path on a local filesystem.
Archetypically  `PosixPath` or `WindowsPath`.
This is used for writing methods that wrap base functionality.
"""
abstract type SystemPath end
```


Possibly it should just be called `Path`
as we already have a pseudoconstructor by that name.

`Path() = @static Sys.isunix() ? PosixPath() : WindowsPath()`

**Comment by rofinn** [comment]
The reason `SystemPath` isn't an abstract type is mostly because I wasn't expecting people to  extended. What else would someone want it to be? While I can get behind making it an abstract type I don't think we should call it `Path` as those constructors are intend for constructing arbitrary path types (e.g., `Path("s3://mybucket/my/prefix/to/obj.tar.gz")` which behaves completely differently than a `SystemPath`).

**Comment by oxinabox** [comment]
What is the breakingness you are forseeing?
It will act the same for dispatch AFAIK,

It won't act the same for `isabstracttype(SystemPath)` but is that the level of breaking we are being sensitive to?
